baseURL = "https://localhost:1313/"
languageCode = "en-us"
title = "Non-academic Academia"
pagination = { pagerSize = 10 }

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Learn academic topics in a simple and engaging way."
