baseURL = "https://non-academic-academia.onrender.com/"
languageCode = "en-us"
title = "Non-academic Academia"
buildFuture = true  # This will allow future-dated content to be built

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Learn academic topics in a simple and engaging way."
  googleAnalytics = "$HUGO_GOOGLE_ANALYTICS"
  keywords = [
    "non-academic academia", "non-academic","academia", "wikipedia", "wiki", "learning", "education", 
    "science", "math", "physics", "astronomy", "chemistry",
    "biology", "computer science", "programming", "coding",
    "personal wiki", "educational blog", "open source learning",
    "classical physics", "modern physics", "physics tutorials",
    "academic resources", "self-learning", "student resources",
    "physics education", "science education", "academic writing",
    "online learning", "educational content", "academic tutorials",
    "wiki learning", "free education", "academic blog",
    "protyasha roy", "physics explanations", "beginner friendly"
]
  images = ["/images/me-rocketto.png"]
  
[sitemap]
  changefreq = "weekly"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON", "SITEMAP"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false  # Keep HTML rendering secure

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^go$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET']
    urls = ['https://cdn.jsdelivr.net/.*']

ignoreLogs = ['warning-goldmark-raw-html']
