baseURL = "https://non-academic-academia.vercel.app/"
languageCode = "en-us"
title = "Non-academic Academia"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Learn academic topics in a simple and engaging way."
