baseURL = "https://non-academic-academia.onrender.com/"
languageCode = "en-us"
title = "Non-academic Academia"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Learn academic topics in a simple and engaging way."
  googleAnalytics = {{ getenv "HUGO_GOOGLE_ANALYTICS" }}

[markup]
